/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface YooForecast {

    }
  }

  interface HTMLYooForecastElement extends StencilComponents.YooForecast, HTMLStencilElement {}

  var HTMLYooForecastElement: {
    prototype: HTMLYooForecastElement;
    new (): HTMLYooForecastElement;
  };
  interface HTMLElementTagNameMap {
    'yoo-forecast': HTMLYooForecastElement;
  }
  interface ElementTagNameMap {
    'yoo-forecast': HTMLYooForecastElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'yoo-forecast': JSXElements.YooForecastAttributes;
    }
  }
  namespace JSXElements {
    export interface YooForecastAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface YooTemperature {
      'myTemperature': number;
    }
  }

  interface HTMLYooTemperatureElement extends StencilComponents.YooTemperature, HTMLStencilElement {}

  var HTMLYooTemperatureElement: {
    prototype: HTMLYooTemperatureElement;
    new (): HTMLYooTemperatureElement;
  };
  interface HTMLElementTagNameMap {
    'yoo-temperature': HTMLYooTemperatureElement;
  }
  interface ElementTagNameMap {
    'yoo-temperature': HTMLYooTemperatureElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'yoo-temperature': JSXElements.YooTemperatureAttributes;
    }
  }
  namespace JSXElements {
    export interface YooTemperatureAttributes extends HTMLAttributes {
      'myTemperature'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;